### ISSUE TITLE
误服此药导致我安装成了centos，怎么办？

### ISSUE THREAD

**Issue by XzaiCloud** [moesoha/debian-media-box#18]

**Comment by KudouShinnyan** [comment]
(CentOS的logo像哪种糖? )

**Comment by moesoha** [comment]
那是买到了盗版吧233

**Comment by rinscr3003** [comment]
> (CentOS的logo像哪种糖? )

It's like the ethernet switch in Cisco Packet Tracker lol
Maybe it's an IOS installer.
