### ISSUE TITLE
说明书编译后内容重叠

### ISSUE THREAD

**Issue by Pinghigh** [moesoha/debian-media-box#19]
如题，中间一列和标题重合了，不是很懂 LaTeX，没啥解决的思路

如图：  
![图片](https://github.com/moesoha/debian-media-box/assets/77083712/b856cb51-85fb-4cfb-8e99-c7a96322169d)

**Comment by moesoha** [comment]
我也不是很懂的说，可能和版本以及编译器之类的有关系？

**Comment by Pinghigh** [comment]
> 我也不是很懂的说，可能和版本以及编译器之类的有关系？

好诡异，直接用 github action 编译的就没有问题

**Comment by moesoha** [comment]
因为这个 header 本身是用了一些魔法做出来的，可能一些语法在新版被砍了也说不定

**Comment by GrandDuke1106** [comment]
一种完全不优雅的方法，直接将中间一列用``\minipage``包裹起来指定距离顶部的长度，这样第一列和第二列可以对齐，第三列顶部也有了标题，更美观一些

overleaf也可以编译

至于为啥原本的代码编译出来是这个样子确实不清楚

![image](https://github.com/user-attachments/assets/c0f295ff-8c42-49d2-a463-b577b6c7a07c)
