### ISSUE TITLE
与正面相对的说明页应该倒过来

### ISSUE THREAD

**Issue by thelastlin** [moesoha/debian-media-box#2]
与正面相对的说明页（即提到硬件要求的那一面）应该倒过来

**Comment by yinyue200** [comment]
但是原版（某药品）的包装好像就是没倒过来的

**Comment by moesoha** [comment]
是的，和 @yinyue200 说的一致。

其实每个人习惯不一样，而且似乎正方形的盒子的话，一般是水平翻转的人比较多。

那这个 issue 就关掉啦
