### ISSUE TITLE
正面背面是不是应该反着？

### ISSUE THREAD

**Issue by mxdabc** [moesoha/debian-media-box#24]
# 正面反过来是倒着的
![photo_2024-07-23_01-47-02](https://github.com/user-attachments/assets/7e1c66a3-f27c-4dea-9fb7-d7849eff1966)

**Comment by moesoha** [comment]
取决于怎么翻转，以垂直轴翻转确实是倒着的，但水平轴翻转就是正着的。在制作时，补佳乐原盒就是以水平轴翻转的。
