### ISSUE TITLE
正反面印刷倒置

### ISSUE THREAD

**Issue by SteveZMTstudios** [moesoha/debian-media-box#27]
![IMG_20241103_132004.jpg](https://github.com/user-attachments/assets/75885810-5a9f-4492-8098-0ef894c937de)

![IMG_20241103_132010.jpg](https://github.com/user-attachments/assets/6e3d177d-3f04-4e17-bfe5-b3c1e321d813)

**Comment by moesoha** [comment]
与 #2 重复。

再解释一遍：
1. 创意的来源补佳乐的盒子就是这样的。
2. 会不会倒过来取决于翻转方式是水平轴还是垂直轴，如果你按照水平轴翻转就不会倒过来了。
