### ISSUE TITLE
写了一个说明书

### ISSUE THREAD

**Issue by SteveCharlesYang** [moesoha/debian-media-box#3]
![info_pages-to-jpg-0001](https://user-images.githubusercontent.com/12855915/60768871-a9f2ae00-a0fb-11e9-9702-7b7aa26bf8b3.jpg)
吼不吼哇？

**Comment by zhao-gang** [comment]
“以根权限在根目录...” root 权限成根权限了 :-)

**Comment by KagurazakaHanabi** [comment]
写成 root 权限好像是为了不换行？

**Comment by moesoha** [comment]
欢迎 pr（

**Comment by AndyChen2005121** [comment]
1. 正式名称那里反了
2. 相互作用那里建议改成 "与其他操作系统的相互作用......"

**Comment by Cathgao** [comment]
不良反应没有关于丢失文件的描述，与说明书开头的参见不符

**Comment by lightsing** [comment]
原文档请求

**Comment by SteveCharlesYang** [comment]
忘记这个了，所以一直咕咕咕...
原文件是 AI 格式的，发给 @moesoha 了，然后 ta 会改成 LaTeX 格式的，方便 diff。
