### ISSUE TITLE
关于有效期的建议

### ISSUE THREAD

**Issue by Cathgao** [moesoha/debian-media-box#7]
有效期建议按照LTS 5年的维护时间来从生产日期+5年得到。虽然到2020年届时真正结束支持的日期可能会不一样，但总体来说还是相差不大的。说明书也适用这一个建议

**Comment by moesoha** [comment]
说明书现在是说明了 36 个月的完整支持和 60 个月的长期支持，这个应当已与 Debian 的 Release EOL、LTS EOL 对齐。

**Comment by moesoha** [comment]
至于封面上的有效期，鉴于 Debian 的说法是 LTS 支持“at least”5 年，所以考虑按照精确到月的 +5 年来计算。
