### ISSUE TITLE
关于药盒尺寸的建议

### ISSUE THREAD

**Issue by sakuraikaede** [moesoha/debian-media-box#8]
如果可以的话，可以在 readme.md 里描述纸盒的尺寸，便于打印。

**Comment by moesoha** [comment]
README 中已经说明了使用 A4 纸打印，就可以获得正确尺寸的盒子。Release 中给出的 pdf 以及 AI 档案中的画布也是按照 A4 纸的大小设置。

我先关掉 issue 了，如果还有别的疑问可以继续回复。
